version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    ports:
      # Expose API port for backend for LOCAL build
       - 81:81
  # PHP FastCGI Process Manager container
  php:
    environment:
      # If you down want to use xDebug, set remote_enable=0
      # XDEBUG LOCAL ONLY
      XDEBUG_CONFIG: "remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
  # mariadb database container
  mariadb:
    ports:
      - 3306

